### ISSUE TITLE
Would you like commit access?

### ISSUE THREAD

**Issue by wizzomafizzo** [gen3vra/starcheat-patched-bin#2]
I am still on github but yes I'm definitely not updating starcheat. If you like I can give you commit access to the main repo to apply your patches. If you'd rather do your own thing that's fine too. I'll add a note to my project pointing to yours.

**Comment by gen3vra** [comment]
Hey there! Thank you, I'd prefer to simply keep as is for now. That note would be very appreciated. :)

**Comment by wizzomafizzo** [comment]
No worries mate. I've added a note to the readme now. If you feel comfortable doing so in the future I'd appreciate if you could submit a pull request of your changes.
