### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by bbepis** [gen3vra/starcheat-patched-bin#4]
Will source-code be released? Wondering since the original project was open-source. If no, would be curious as to the reason why not

**Comment by gen3vra** [comment]
unfortunately no, it will not be

if you want to create your own fork or project you may use https://github.com/wizzomafizzo/starcheat

**Comment by bbepis** [comment]
Can I ask why? This is the only project I can find on the internet that apparently is able to understand v1.0 data. [py-starbound](https://github.com/blixt/py-starbound) has very little information on player data, and I'm not sure if it can actually handle v1.0 versioned data

The repo you linked only supports a 6+ year old beta copy of starbound

**Comment by bbepis** [comment]
So you're fine with stealing source code from Chucklefish but not releasing your changes to someone else's codebase?

**Comment by bbepis** [comment]
@gen3vra
