### ISSUE TITLE
[BUG] MSVCP100.dll could not be extracted!

### ISSUE THREAD

**Issue by Cinnamon42** [gen3vra/starcheat-patched-bin#7]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please MAKE SURE this is accurate):**
 - OS: [e.g. Windows/Mac]
 - Player species:
 - Starcheat Version:

**Additional context/Clarification questions** _IF NEEDED_
![캡처](https://user-images.githubusercontent.com/98933225/171860236-f2069e1c-161d-4e73-a1ff-b5948e980d6f.PNG)

**Comment by gen3vra** [comment]
I have no information about the machine you're trying to use Starcheat on.

My best guess is that either a) your antivirus is blocking the program from extracting the necessary files to appdata, or b) you don't have the dll at all: 
https://answers.microsoft.com/en-us/windows/forum/all/msvcp100dll-missing/9a687c31-0619-4ee9-b511-020985e29b5f

You should install both of these and try again:
http://www.microsoft.com/en-in/download/details.aspx?id=5555
http://www.microsoft.com/en-us/download/details.aspx?id=14632

If it doesn't work, provide more information about your environment like asked in the form you didn't fill out.

**Comment by gen3vra** [comment]
Feel free to reopen if you have more info to share
